#pragma once

// UART 1 CONFIG DEFINES
#define UART_NUM UART_NUM_1
#define UART_TX_PIN 25
#define UART_RX_PIN 26
#define UART_BAUDRATE 115200
#define UART_DATA_BITS UART_DATA_8_BITS
#define UART_STOP_BITS UART_STOP_BITS_1
#define UART_PARITY UART_PARITY_DISABLE

#define PATTERN_CHR_NUM (3)
#define PATTERN_CHR_TIMEOUT (9)
#define UART_BUF_SIZE (1024)

// WIFI STA DEFINES
// #define WIFI_STA_SSID "SIETECOLORES"
// #define WIFI_STA_PSWD "QWE&ASD%ZXC#!!"

// COMMAND DEFINES
#define COMMAND_NUM_ARGS_MAX 5
#define END_PATTERN "+++"
#define SPLIT_PATTERN " "

#define AT_INITSTATION "AT+InitStation"
#define COMMAND_INITSTATION_OK (AT_INITSTATION SPLIT_PATTERN "OK" END_PATTERN)
#define COMMAND_INITSTATION_FAILED (AT_INITSTATION SPLIT_PATTERN "FAILED" END_PATTERN)

#define AT_DEINITSTATION "AT+DeinitStation"
#define COMMAND_DEINITSTATION_OK (AT_DEINITSTATION SPLIT_PATTERN "OK" END_PATTERN)

#define AT_HTTPPOST "AT+HttpPost"
#define COMMAND_HTTPPOST_FAILED (AT_HTTPPOST SPLIT_PATTERN "FAILED" END_PATTERN)
