#pragma once

// UART 1 CONFIG DEFINES
#define UART_NUM UART_NUM_1
#define UART_TX_PIN 25
#define UART_RX_PIN 26
#define UART_BAUDRATE 115200
#define UART_DATA_BITS UART_DATA_8_BITS
#define UART_STOP_BITS UART_STOP_BITS_1
#define UART_PARITY UART_PARITY_DISABLE

#define PATTERN_CHR_NUM (3)
#define PATTERN_CHR_TIMEOUT (9)
#define UART_BUF_SIZE (1024)

// WIFI STA DEFINES
//#define WIFI_STA_SSID "SIETECOLORES"
//#define WIFI_STA_PSWD "QWE&ASD%ZXC#!!"

// COMMAND DEFINES
#define COMMAND_NUM_ARGS_MAX 5
#define END_PATTERN "+++"

#define AT_INITSTATION "AT+InitStation"
#define INITSTATION_OK "InitStation=OK"
#define COMMAND_INITSTATION_OK (INITSTATION_OK END_PATTERN)
#define INITSTATION_FAILED "InitStation=FAILED"
#define COMMAND_INITSTATION_FAILED (INITSTATION_FAILED END_PATTERN)

#define AT_DEINITSTATION "AT+DeinitStation"
#define DEINITSTATION_OK "DeinitStation=OK"
#define COMMAND_DEINITSTATION_OK (DEINITSTATION_OK END_PATTERN)




